#!/bin/sh
NAME="systemd"
VERSION="254"
SOURCES="https://github.com/systemd/systemd/archive/refs/tags/v$VERSION.tar.gz"
BUILD_DEPENDS="meson samurai gnu-coreutils"
DEPENDS="gperf libcap util-linux python-jinja2 kmod"
SHA256SUM="244da7605800a358915e4b45d079b0b89364be35da4bc8d849821e67bac0ce62  v254.tar.gz"
DESCRIPTION="The systemd System and Service Manager"

build() {
    meson --prefix=/usr build/
    ninja -C build/
}

package() {
    DESTDIR=$ROOT ninja -C build/ install
}
